### ISSUE TITLE
Battery indicator stays red always

### ISSUE THREAD

**Issue by NithishkumarS** [jackal/jackal_firmware_ms#2]
I charged the jackal's battery to it full as indicated in the charger (green led). But when connected to Jackal the battery indicator on the dashboard of jackal shows red. This happedend after I charged my battery after a test run. 
I tried testing it with another spare battery as well. Gave the same response.
How do I solve it?

**Comment by tonybaltovski** [comment]
Can you please provide the version of the MCU firmware by running `rostopic echo -n1 /status/hardware_id`?

**Comment by NithishkumarS** [comment]
I am not able to turn it on to SSH into the robot. Sorry about not being able to provide more details. But the OS version is kinetic-jackal-amd64-0.4.2

**Comment by NithishkumarS** [comment]
The MCU and the processer seem to recieve power from the battery, as tested with a multimeter. Yet, when I try to ssh into the system via LAN cable, shows unable to communicate with ROS Master

**Comment by NithishkumarS** [comment]
Issue came up becasue of the accidental push of the firmware update button
