### ISSUE TITLE
Will this firmware update Jackal to 0.4.3?

### ISSUE THREAD

**Issue by AnthonyZJiang** [jackal/jackal_firmware_ms#3]
Our jackal's hardware id is 0.3.9 according to `\status`. Can we use this firmware to update it to 0.4.3?

**Comment by tonybaltovski** [comment]
@tmxkn1 are you using windows?  If not, you can update your jackal's firmware using: https://www.clearpathrobotics.com/assets/guides/melodic/jackal/update.html

**Comment by AnthonyZJiang** [comment]
> @tmxkn1 are you using windows? If not, you can update your jackal's firmware using: https://www.clearpathrobotics.com/assets/guides/melodic/jackal/update.html

Thank you!
